# Generated by Django 4.2.19 on 2025-03-30 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0004_investment_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_spent', models.FloatField()),
                ('total_amount_target', models.FloatField()),
                ('suggestions', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.FloatField()),
                ('current_savings', models.FloatField()),
                ('goal_date', models.DateField()),
                ('monthly_savings_required', models.FloatField()),
                ('converted_currency', models.CharField(default='USD', max_length=10)),
                ('monthly_savings_converted', models.FloatField(blank=True, null=True)),
                ('etf_symbol', models.CharField(blank=True, max_length=20)),
                ('etf_price', models.FloatField(blank=True, null=True)),
                ('etf_change', models.FloatField(blank=True, null=True)),
                ('email_status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='savings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Savings',
        ),
    ]
